# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcfec51ce8b230ae7a08b931cb9b614a39558606fd12eac354103250e8d7e2f61ac3a790790dfdb6e3e7ee13e4ec0b02759c2c8ca810e8e9d4c9eb055c730653

test:
  secret_key_base: 5f8aec06a37b9288aeb6705292edab01e5363e21daaa1264ecde58b8cd47464eeb5c7ca445e54ec72178b942405d5a2496aa02b67a301c2eee5ecacfcc1a3f18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
